version: '2.1'

services:
  flask-base-db:
    container_name: flask-base-db
    build: ./project/db
    ports:
      - 5435:5432  # expose ports - HOST:CONTAINER
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: exit 0

  flask-base-service:
    container_name: flask-base-service
    build: .
    volumes:
      - '.:/usr/src/app'
    ports:
      - 5001:5000 # expose ports - HOST:CONTAINER
    environment:
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@flask-base-db:5432/flask_base_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@flask-base-db:5432/flask_base_test
    depends_on:
      flask-base-db:
        condition: service_healthy
    links:
      - flask-base-db

  nginx:
    container_name: nginx
    build: ./nginx/
    restart: always
    ports:
      - 80:80
    depends_on:
      flask-base-service:
        condition: service_started
    links:
      - flask-base-service
